-- ==========================================
-- BANK TRANSACTION ANALYSIS PROJECT
-- Database: Oracle SQL
-- File: create_tables.sql
-- ==========================================

-- 1. CUSTOMERS TABLE
CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50),
    CITY VARCHAR2(30),
    PHONE NUMBER(10)
);

-- 2. BRANCHES TABLE
CREATE TABLE BRANCHES
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR2(50),
    CITY VARCHAR2(30)
);

-- 3. ACCOUNTS TABLE
CREATE TABLE ACCOUNTS
(
    ACCOUNT_NO NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    BRANCH_ID NUMBER REFERENCES BRANCHES(BRANCH_ID),
    ACCOUNT_TYPE VARCHAR2(20),
    BALANCE NUMBER(10,2)
);

-- 4. TRANSACTIONS TABLE
CREATE TABLE TRANSACTIONS
(
    TRANSACTION_ID NUMBER PRIMARY KEY,
    ACCOUNT_NO NUMBER REFERENCES ACCOUNTS(ACCOUNT_NO),
    TRANSACTION_DATE DATE,
    TRANSACTION_TYPE VARCHAR2(20),
    AMOUNT NUMBER(10,2)
);
